# Rive build options and paths (project root = top-level source dir)
set(RIVE_RUNTIME_DIR "${CMAKE_SOURCE_DIR}")

option(RIVE_WITH_TEXT "Build with text features" ON)
option(RIVE_WITH_LAYOUT "Build with layout (Yoga)" ON)
option(RIVE_WITH_AUDIO "Build with miniaudio" ON)
option(RIVE_WITH_SCRIPTING "Build with scripting" OFF)
option(RIVE_NO_PNG "Disable PNG support in decoders" OFF)
option(RIVE_NO_JPEG "Disable JPEG support in decoders" OFF)
option(RIVE_NO_WEBP "Disable WebP support in decoders" OFF)
option(RIVE_NO_HARFBUZZ_RENAMES "Disable harfbuzz symbol renames" OFF)
option(RIVE_NO_YOGA_RENAMES "Disable yoga symbol renames" OFF)

if(WIN32)
  set(RIVE_PLATFORM "windows")
elseif(APPLE)
  set(RIVE_PLATFORM "macosx")
else()
  set(RIVE_PLATFORM "linux")
endif()

# Dependencies path (after running scripts/download_deps.sh)
set(RIVE_DEPS_DIR "${RIVE_RUNTIME_DIR}/dependencies")
set(GLFW_DIR "${RIVE_DEPS_DIR}/glfw_glfw_3.4")
set(HARFBUZZ_DIR "${RIVE_DEPS_DIR}/rive-app_harfbuzz_rive_13.1.1")
set(SHEENBIDI_DIR "${RIVE_DEPS_DIR}/Tehreer_SheenBidi_v2.6")
set(YOGA_DIR "${RIVE_DEPS_DIR}/rive-app_yoga_rive_changes_v2_0_1_2")
set(MINIAUDIO_DIR "${RIVE_DEPS_DIR}/rive-app_miniaudio_rive_changes_5")
set(ZLIB_DIR "${RIVE_DEPS_DIR}/madler_zlib_v1.3.1")
set(LIBPNG_DIR "${RIVE_DEPS_DIR}/glennrp_libpng_libpng16")
set(LIBJPEG_DIR "${RIVE_DEPS_DIR}/rive-app_libjpeg_v9f")
set(LIBWEBP_DIR "${RIVE_DEPS_DIR}/webmproject_libwebp_v1.4.0")
